server:
  type: BPP 
  port: 5500 
  sync_mode: false
security:
  verify_sign: false
  lookup_uri: "http://localhost:3000/lookup"
  generate_sign: true
  subscriber_id: mock-api-service
  ukId: 584
  publickey: 5RF/CSTd5Cksh7xKNE/vr9IlwrV9LT1ZPR8RDeOpWjs=
  privatekey: dYo7zgyKYYoGQiVa45qfTQ94ic0bXPjN5KiUMVX0NBHlEX8JJN3kKSyHvEo0T++v0iXCtX0tPVk9HxEN46laOw==
log:
  level: DEBUG
  output_type: file
  out_file: log_file.log
path:
  sign:
    schema:
      type: object
    callbacks:
      default:
        payload:
          template:
            data:
              $ref: "./v1/search.yaml"
  search:
    schema:
      $ref: "./schema/search.json"
    callbacks:
      $ref: "./v1/search.yaml"
  select:
    schema:
      $ref: "./schema/select.json"
    callbacks:
      $ref: "./v1/select.yaml"
  init:
    schema:
      $ref: "./schema/init.json"
    callbacks:
      $ref: "./v1/init.yaml"
  confirm:
    schema:
      $ref: "./schema/confirm.json"
    callbacks:
      $ref: "./v1/confirm.yaml"
  status:
    schema:
      $ref: "./schema/status.json"
    callbacks:
      $ref: "./v1/status.yaml"
  update:
    schema:
      $ref: "./schema/update.json"
    callbacks:
      $ref: "./v1/update.yaml"
  support:
    schema:
      $ref: "./schema/support.json"
    callbacks:
      $ref: "./v1/support.yaml"
  track:
    schema:
      $ref: "./schema/track.json"
    callbacks:
      $ref: "./v1/track.yaml"
  rating:
    schema:
      $ref: "./schema/rating.json"
    callbacks:
      $ref: "./v1/rating.yaml"
  on_search:
    schema:
      $ref: "./schema/on_search.json"
    callbacks:
      $ref: "./v1/on_search.yaml"
  on_select:
    schema:
      $ref: "./schema/on_select.json"
    callbacks:
      $ref: "./v1/on_select.yaml"
  on_init:
    schema:
      $ref: "./schema/on_init.json"
    callbacks:
      $ref: "./v1/on_init.yaml"
  on_confirm:
    schema:
      $ref: "./schema/on_confirm.json"
    callbacks:
      $ref: 
  on_status:
    schema:
      $ref: "./schema/on_status.json"
    callbacks:
      $ref: 
  on_update:
    schema:
      $ref: "./schema/on_update.json"
    callbacks:
      $ref: 
  on_track:
    schema:
      $ref: "./schema/on_track.json"
    callbacks:
      $ref: 
  on_support:
    schema:
      $ref: "./schema/on_support.json"
    callbacks:
      $ref: 
  on_rating:
    schema:
      $ref: "./schema/on_rating.json"
    callbacks:
      $ref: 
 